# Generated by Django 4.1 on 2022-08-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_transacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='observacoes',
            field=models.TextField(default=''),
        ),
    ]
