# Generated by Django 4.1 on 2022-08-29 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0008_alter_transacao_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='descriçao',
            new_name='descricao',
        ),
    ]
